import { Space, Typography } from 'antd';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

import gamesImg from '../../public/assets/images/cat.png';

const { Text } = Typography;

function Games() {
  const gameList = [
    { name: 'Collection 1', id: '100001', price: 1000 },
    { name: 'Collection 2', id: '100002', price: 1000 },
    { name: 'Collection 3', id: '100003', price: 1000 },
    { name: 'Collection 4', id: '100004', price: 1000 },
    { name: 'Collection 5', id: '100005', price: 1000 },
  ];

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ paddingTop: '100px', paddingBottom: '200px' }}>
        <Text
          style={{
            display: 'inline-block',
            fontSize: '40px',
            lineHeight: '48px',
            fontWeight: '700',
            marginTop: '26px',
            marginBottom: '26px',
            width: '100%',
          }}
        >
          Games
        </Text>

        <section
          style={{
            display: 'grid',
            gridGap: '20px',
            gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
          }}
        >
          {gameList.map((game) => (
            <Link
              href={`/games/${game.id}`}
              key={game.id}
              style={{ width: '100%' }}
            >
              <div
                style={{
                  padding: '14px',
                  width: '285px',
                  minHeight: '384px',
                  boxShadow: '0px 10px 30px rgba(0, 0, 0, 0.08)',
                  display: 'block',
                  overflow: 'hidden',
                  boxSizing: 'border-box',
                  borderRadius: '20px',
                }}
              >
                <Image
                  src={gamesImg}
                  width={257}
                  height={257}
                  alt="games"
                  style={{ borderRadius: '12px' }}
                />
                <Space direction="vertical" style={{ padding: '14px 6px' }}>
                  <Text
                    style={{
                      lineHeight: '20px',
                      fontSize: '16px',
                      whiteSpace: 'nowrap',
                      fontWeight: '700',
                    }}
                  >
                    {game.name}
                  </Text>
                  <Text
                    style={{
                      lineHeight: '20px',
                      fontSize: '16px',
                      whiteSpace: 'nowrap',
                      fontWeight: '700',
                      marginTop: '2px',
                    }}
                  >
                    {game.price} Matic
                  </Text>
                </Space>
              </div>
            </Link>
          ))}
        </section>
      </main>
    </>
  );
}

export default Games;
